repos:
  - repo: local
    hooks:
      - id: run-pytest-pre-commit
        name: run-pytest-pre-commit
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        verbose: true

