[project]
name = "lirs"
version = "0.1.0"
description = "LIRS is a Less Irritating R Server"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.3.5",
    "flask>=3.1.0",
    "flask-cors>=5.0.1"
]
